---
title: "2_explore"
output: html_notebook
editor_options: 
  chunk_output_type: console
---
 
# Import library

```{r}

rm (list = ls())

# Helper
library (tidyverse)

# Import
library (rio)

# Exploration 
library (DataExplorer)
library (janitor)
library (arsenal)
library (ggforce)
library (gganimate)

# functional plots and outliers
library (rainbow)
library (mrfDepth)

# modelling
library (FDboost)

# parallel
library(doParallel)
library(foreach)
library (furrr)

# custom 

source ("code/extract_from_mat.R")

```

# Import raw data

```{r}

output_dir <- "output"
file_name <- "df_combined.RDS"

df.list <- readRDS (file.path(output_dir, file_name))


```

# Restruture data

```{r}
df <- df.list %>%
  map (~.$biomech) %>%
  bind_rows() %>%
  separate(task, into = c("task", "rep"), sep = "_")

```

# Correct left ankle angles

```{r}

df2 <- df %>%
  mutate_if (is.character, ~tolower(.)) %>%
  mutate (task = str_trim (task),
          var_axis = str_trim (var_axis),
          val = ifelse (side == "lx" & var_axis == "ankleadd", val * -1, 
                        ifelse (task %in% c("toewalking", "walking") & side == "lx" & var_axis == "anklerot", val * -1, val)))

```


# Plot
 
```{r}

df_plot <- df2 %>%
  group_by(task, var_axis, side, cycle) %>%
  summarize (Mean = mean (val, na.rm = TRUE)) %>%
  ungroup()

f <- ggplot (data= df_plot) +
  geom_line (aes (x = cycle, y = Mean, colour = side)) +
  facet_wrap_paginate(task ~ var_axis, ncol = 5, nrow = 5, scales = "free", page = 1)

fig_name <- "explore_plot.pdf"

n <- n_pages(f)

pdf (width = 10, height = 8, file = file.path(output_dir, fig_name))
for(i in 1:n){
    print(f + facet_wrap_paginate(task ~ var_axis, ncol = 5, nrow = 5, scales = "free", page = i))
}
dev.off()




```


# Animated plots
## Joint power

```{r}

jtpwr <- c("AnklePwr", "KneePwr", "HipPwr")
df_plot <- df2 %>%
  filter (task == "Walking" & var_axis %in% jtpwr) %>%
  mutate (var_axis = factor (var_axis, levels = jtpwr)) %>%
  group_by( age, var_axis, cycle) %>% 
  summarise(val = mean (val))

f <- animate(
ggplot (data= df_plot, aes (x = cycle, y = val, colour = age)) +
  geom_line(alpha = 0.7) +
  facet_wrap(~ var_axis) +
  transition_time (age, range = c(6, 72)) +
  labs(title = "Age: {frame_time}") +
  view_follow(fixed_y = TRUE),
fps = 20, 
renderer = av_renderer()
)
output_dir <- "output"
file_name <- "pwr_anim_plot.mp4"
anim_save(filename = file.path(output_dir, file_name), animation = f)


```



# Export data
 
```{r}

output_dir <- "output"
file_name <- "df_clean.RDS"

saveRDS(df2, file = file.path(output_dir, file_name))

```
