---
title: "3_gamlss_analysis"
output: html_notebook
editor_options: 
  chunk_output_type: console
---
  
# Import library
  
```{r}

library(mgcv)
library(dplyr)
library(tidyr)
library(parallel)
library(gamlss)
library(gamlss.dist)
library(gamlss.add)
library(ParBayesianOptimization)
library(parallel)

roundBelow3 <- function(x) ifelse(x<3,0,x)


source("code/measures_johnson.R")
source("code/settings_to_formula.R")


```

```{r, include=FALSE}
knitr::opts_chunk$set(
  eval = FALSE
)
```

# Bayesian optimization

## Tune smoothing parameters and covariates

### Ankle

```{r}
# Load data --------------------------------------------------------------------

data <- readRDS("output/ankle_splitted.RDS")
train <- do.call("rbind", data[c(1,3)])
test <- data[[2]]
test <- test %>% arrange(subj, cycle)
# create true functional matrix
# with 49 observations, 1 row = 1 subject
trueMat <- test %>% spread(cycle, val) %>% dplyr::select(`21`:`69`) %>% as.matrix()
# does not look too good though (?)
matplot(t(trueMat), type="l", col = 
          test %>% 
          filter(cycle==21) %>% 
          pull(study) %>% as.numeric)
rm(data)

# Define objective function ----------------------------------------------------

scoringFunction <- function(
  k_cycle, 
  k_age,
  k_speed,
  k_cycle_age_1,
  k_cycle_age_2,
  k_cycle_speed_1,
  k_cycle_speed_2,
  k_age_speed_1,
  k_age_speed_2,
  k_cycle_age_speed_1,
  k_cycle_age_speed_2,
  k_cycle_age_speed_3,
  k_cycle_ht_1,
  k_cycle_ht_2,
  k_ht,
  k_strlen,
  k_cycle_strlen_1,
  k_cycle_strlen_2,
  # k_cycle_re,
  cycle_age
) {
  
  # funargs <- as.list(match.call())[-1]
  # if(any(unlist(funargs)<3) & unlist(funargs)>0) 
  #   return(do.call("replaceScore", lapply(funargs, function(x) pmax(3,x))))
  
  k_cycle <- roundBelow3(k_cycle)
  k_age <- roundBelow3(k_age)
  k_speed <- roundBelow3(k_speed)
  k_cycle_age_1 <- roundBelow3(k_cycle_age_1)
  k_cycle_age_2 <- roundBelow3(k_cycle_age_2)
  k_cycle_speed_1 <- roundBelow3(k_cycle_speed_1)
  k_cycle_speed_2 <- roundBelow3(k_cycle_speed_2)
  k_age_speed_1 <- roundBelow3(k_age_speed_1)
  k_age_speed_2 <- roundBelow3(k_age_speed_2)
  k_cycle_age_speed_1 <- roundBelow3(k_cycle_age_speed_1)
  k_cycle_age_speed_2 <- roundBelow3(k_cycle_age_speed_2)
  k_cycle_age_speed_3 <- roundBelow3(k_cycle_age_speed_3)
  k_cycle_ht_1 <- roundBelow3(k_cycle_ht_1)
  k_cycle_ht_2 <- roundBelow3(k_cycle_ht_2)
  k_ht <- roundBelow3(k_ht)
  k_strlen <- roundBelow3(k_strlen)
  k_cycle_strlen_1 <- roundBelow3(k_cycle_strlen_1)
  k_cycle_strlen_2 <- roundBelow3(k_cycle_strlen_2)
  # k_cycle_re <- roundBelow3(k_cycle_re)
  
  bs <-  "cr"
  
  form <-  paste0("val ~ ",
                  "ti (cycle, k = k_cycle, bs = bs) + ",
                  "ti (age, k = k_age, bs = bs) + ",
                  "ti (speed, k = k_speed, bs = bs) + ",
                  "ti(ht, k = k_ht, bs = bs) + ",
                  "ti(strlen, k = k_strlen, bs = bs) + ",
                  "sex ")
  
  if(all(c(k_cycle_age_1, 
           k_cycle_age_2)>0))
    form <- paste0(form, 
                   "+ ti (cycle, age, k = c(k_cycle_age_1, k_cycle_age_2), bs = bs)")
  if(all(c(k_cycle_speed_1, 
           k_cycle_speed_2)>0))
    form <- paste0(form, 
                   "+ ti (cycle, speed, k = c(k_cycle_speed_1, k_cycle_speed_2),  bs = bs)")
  if(all(c(k_age_speed_1, 
           k_age_speed_2)>0))
    form <- paste0(form, 
                   "+ ti (age, speed,  k = c(k_age_speed_1, k_age_speed_2),  bs = bs)")
  if(all(c(
    k_cycle_age_1, 
    k_cycle_age_2,
    k_cycle_speed_1, 
    k_cycle_speed_2,
    k_age_speed_1, 
    k_age_speed_2,
    k_cycle_age_speed_1, 
    k_cycle_age_speed_2,
    k_cycle_age_speed_3)>0))
    form <- paste0(form, 
                   "+ ti (cycle, speed, age,  k = c(k_cycle_age_speed_1, k_cycle_age_speed_2,",
                   " k_cycle_age_speed_3), bs = bs)"
    )
  if(all(c(k_cycle_ht_1, 
           k_cycle_ht_2)>0))
    form <- paste0(form, 
                   "+ ti (cycle, ht, k = c(k_cycle_ht_1, k_cycle_ht_2), bs = bs)")
  if(all(c(k_cycle_strlen_1, 
           k_cycle_strlen_2)>0))
    form <- paste0(form, 
                   "+ ti (cycle, strlen, k = c(k_cycle_strlen_1, k_cycle_strlen_1), bs = bs)")
  # if(k_cycle_re>0)
  #   form <- paste0(form, 
  #                  "+ ti (cycle, k = k_cycle_re, by = study, bs = 're')")
  
  form <- as.formula(form)
  
  pr <- try({
    
    mod <- bam (form,
                data = train,
                discrete = TRUE,
                family = scat()
    )
    
    predict(mod, newdata = test)#, exclude = "s(subj)")
    
  })
  
  if(class(pr)=="try-error") score <- NA else{
    
    test$pr <- pr
    predMat <- test %>% dplyr::select(-val) %>% spread(cycle, pr) %>% 
      dplyr::select(`21`:`69`) %>% as.matrix()
    score <- -mean(relRMSE(trueMat, predMat), na.rm=T)
    
  
  }
    
  return(list(Score = score))
}

replaceScore <- scoringFunction

bounds <- list( 
  k_cycle = c(5L,25L), 
  k_age = c(5L,20L),
  k_speed = c(5L,20L),
  k_cycle_age_1 = c(0L,25L),
  k_cycle_age_2 = c(0L,20L),
  k_cycle_speed_1 = c(0L,25L),
  k_cycle_speed_2 = c(0L,6L),
  k_age_speed_1 = c(0L,20L),
  k_age_speed_2 = c(0L,6L),
  k_cycle_age_speed_1 = c(0L,15L),
  k_cycle_age_speed_2 = c(0L,10L),
  k_cycle_age_speed_3 = c(0L,6L),
  k_cycle_ht_1 = c(0L,25L),
  k_cycle_ht_2 = c(0L,15L),
  k_cycle_strlen_1 = c(0L,15L),
  k_cycle_strlen_2 = c(0L,15L),
  k_ht = c(5L,15L),
  k_strlen = c(5L, 20L)#,
  # k_cycle_re = c(5L,25L)
)


# Start BO ------------------------------------------------------------------------

nrClusters <- 30
nrEpochs <- 10

library(doParallel)
cl <- makeCluster(nrClusters)
registerDoParallel(cl)
clusterExport(cl,c('train','test','trueMat','relRMSE', 'RMSE', 'integrate_fun', 'roundBelow3'))
clusterEvalQ(cl,expr= {
  library(mgcv)
  library(tidyr)
  library(dplyr)
})

set.seed(42)

tWithPar <- system.time(
  optObj <- bayesOpt(
    FUN = scoringFunction,
    bounds = bounds,
    initPoints = nrClusters,
    iters.n = nrClusters * nrEpochs,
    iters.k = nrClusters,
    parallel = TRUE,
    verbose = 2,
    errorHandling = "continue"
  )
)
stopCluster(cl)
registerDoSEQ()

saveRDS(optObj, file="output/BO_ankle.RDS")
print(tWithPar)

getBestPars(optObj)
```

### Knee

```{r}
# Load data --------------------------------------------------------------------

data <- readRDS("output/knee_splitted.RDS")
train <- do.call("rbind", data[c(1,3)])
test <- data[[2]]
test <- test %>% arrange(subj, cycle)
# create true functional matrix
# with 49 observations, 1 row = 1 subject
trueMat <- test %>% spread(cycle, val) %>% dplyr::select(`1`:`101`) %>% as.matrix()
# does not look too good though (?)
matplot(t(trueMat), type="l", col = 
          test %>% 
          filter(cycle==21) %>% 
          pull(study) %>% as.numeric)

rm(data)

# Define objective function ----------------------------------------------------

scoringFunction <- function(
  k_cycle, 
  k_age,
  k_speed,
  k_cycle_age_1,
  k_cycle_age_2,
  k_cycle_speed_1,
  k_cycle_speed_2,
  k_age_speed_1,
  k_age_speed_2,
  k_cycle_age_speed_1,
  k_cycle_age_speed_2,
  k_cycle_age_speed_3,
  k_cycle_ht_1,
  k_cycle_ht_2,
  k_ht,
  k_strlen,
  k_cycle_strlen_1,
  k_cycle_strlen_2,
  # k_cycle_re,
  cycle_age
) {
  
  # funargs <- as.list(match.call())[-1]
  # if(any(unlist(funargs)<3 & unlist(funargs)>0)) 
  #   return(do.call("replaceScore", lapply(funargs, function(x) pmax(3,x))))
  
  k_cycle <- roundBelow3(k_cycle)
  k_age <- roundBelow3(k_age)
  k_speed <- roundBelow3(k_speed)
  k_cycle_age_1 <- roundBelow3(k_cycle_age_1)
  k_cycle_age_2 <- roundBelow3(k_cycle_age_2)
  k_cycle_speed_1 <- roundBelow3(k_cycle_speed_1)
  k_cycle_speed_2 <- roundBelow3(k_cycle_speed_2)
  k_age_speed_1 <- roundBelow3(k_age_speed_1)
  k_age_speed_2 <- roundBelow3(k_age_speed_2)
  k_cycle_age_speed_1 <- roundBelow3(k_cycle_age_speed_1)
  k_cycle_age_speed_2 <- roundBelow3(k_cycle_age_speed_2)
  k_cycle_age_speed_3 <- roundBelow3(k_cycle_age_speed_3)
  k_cycle_ht_1 <- roundBelow3(k_cycle_ht_1)
  k_cycle_ht_2 <- roundBelow3(k_cycle_ht_2)
  k_ht <- roundBelow3(k_ht)
  k_strlen <- roundBelow3(k_strlen)
  k_cycle_strlen_1 <- roundBelow3(k_cycle_strlen_1)
  k_cycle_strlen_2 <- roundBelow3(k_cycle_strlen_2)
  # k_cycle_re <- roundBelow3(k_cycle_re)
  
  bs <-  "cr"
  
  form <-  paste0("val ~ ",
                  "ti (cycle, k = k_cycle, bs = bs) + ",
                  "ti (age, k = k_age, bs = bs) + ",
                  "ti (speed, k = k_speed, bs = bs) + ",
                  "ti(ht, k = k_ht, bs = bs) + ",
                  "ti(strlen, k = k_strlen, bs = bs) + ",
                  "sex ")
  
  if(all(c(k_cycle_age_1, 
           k_cycle_age_2)>0))
    form <- paste0(form, 
                   "+ ti (cycle, age, k = c(k_cycle_age_1, k_cycle_age_2), bs = bs)")
  if(all(c(k_cycle_speed_1, 
           k_cycle_speed_2)>0))
    form <- paste0(form, 
                   "+ ti (cycle, speed, k = c(k_cycle_speed_1, k_cycle_speed_2),  bs = bs)")
  if(all(c(k_age_speed_1, 
           k_age_speed_2)>0))
    form <- paste0(form, 
                   "+ ti (age, speed,  k = c(k_age_speed_1, k_age_speed_2),  bs = bs)")
  if(all(c(
    k_cycle_age_1, 
    k_cycle_age_2,
    k_cycle_speed_1, 
    k_cycle_speed_2,
    k_age_speed_1, 
    k_age_speed_2,
    k_cycle_age_speed_1, 
    k_cycle_age_speed_2,
    k_cycle_age_speed_3)>0))
    form <- paste0(form, 
                   "+ ti (cycle, speed, age,  k = c(k_cycle_age_speed_1, k_cycle_age_speed_2, k_cycle_age_speed_3), bs = bs)"
    )
  if(all(c(k_cycle_ht_1, 
           k_cycle_ht_2)>0))
    form <- paste0(form, 
                   "+ ti (cycle, ht, k = c(k_cycle_ht_1, k_cycle_ht_2), bs = bs)")
  if(all(c(k_cycle_strlen_1, 
           k_cycle_strlen_2)>0))
    form <- paste0(form, 
                   "+ ti (cycle, strlen, k = c(k_cycle_strlen_1, k_cycle_strlen_1), bs = bs)")
  # if(k_cycle_re>0)
  #   form <- paste0(form, 
  #                  "+ ti (cycle, k = k_cycle_re, by = study, bs = 're')")
  
  form <- as.formula(form)
  
  pr <- try({
    
    mod <- bam (form,
                data = train,
                discrete = TRUE,
                family = scat()
    )
    
    predict(mod, newdata = test)#, exclude = "s(subj)")
    
  })
  
  if(class(pr)=="try-error") score <- NA else{
    
    test$pr <- pr
    predMat <- test %>% dplyr::select(-val) %>% spread(cycle, pr) %>% dplyr::select(`1`:`101`) %>% as.matrix()
    score <- -mean(relRMSE(trueMat, predMat), na.rm=T)
    
    
  }
  
  return(list(Score = score))
}

replaceScore <- scoringFunction

bounds <- list( 
  k_cycle = c(5L,25L), 
  k_age = c(5L,20L),
  k_speed = c(5L,20L),
  k_cycle_age_1 = c(0L,25L),
  k_cycle_age_2 = c(0L,20L),
  k_cycle_speed_1 = c(0L,25L),
  k_cycle_speed_2 = c(0L,6L),
  k_age_speed_1 = c(0L,20L),
  k_age_speed_2 = c(0L,6L),
  k_cycle_age_speed_1 = c(0L,15L),
  k_cycle_age_speed_2 = c(0L,10L),
  k_cycle_age_speed_3 = c(0L,6L),
  k_cycle_ht_1 = c(0L,25L),
  k_cycle_ht_2 = c(0L,15L),
  k_cycle_strlen_1 = c(0L,15L),
  k_cycle_strlen_2 = c(0L,15L),
  k_ht = c(5L,15L),
  k_strlen = c(5L, 20L)#,
  # k_cycle_re = c(5L,25L)
)


# Start BO ------------------------------------------------------------------------

nrClusters <- 30
nrEpochs <- 10

library(doParallel)
cl <- makeCluster(nrClusters)
registerDoParallel(cl)
clusterExport(cl,c('train','test','trueMat','relRMSE', 'RMSE', 'integrate_fun', 'roundBelow3'))
clusterEvalQ(cl,expr= {
  library(mgcv)
  library(tidyr)
  library(dplyr)
})

set.seed(42)

tWithPar <- system.time(
  optObj <- bayesOpt(
    FUN = scoringFunction,
    bounds = bounds,
    initPoints = nrClusters,
    iters.n = nrClusters * nrEpochs,
    iters.k = nrClusters,
    parallel = TRUE,
    verbose = 2,
    errorHandling = "continue"
  )
)
stopCluster(cl)
registerDoSEQ()

saveRDS(optObj, file="output/BO_knee.RDS")
print(tWithPar)

getBestPars(optObj)
```

### Hip

```{r}
# Load data --------------------------------------------------------------------

data <- readRDS("output/hip_splitted.RDS")
train <- do.call("rbind", data[c(1,3)])
test <- data[[2]]
test <- test %>% arrange(subj, cycle)
# create true functional matrix
# with 49 observations, 1 row = 1 subject
trueMat <- test %>% spread(cycle, val) %>% dplyr::select(`1`:`101`) %>% as.matrix()
# does not look too good though (?)
matplot(t(trueMat), type="l", col = 
          test %>% 
          filter(cycle==21) %>% 
          pull(study) %>% as.numeric)
rm(data)

# Define objective function ----------------------------------------------------

scoringFunction <- function(
  k_cycle, 
  k_age,
  k_speed,
  k_cycle_age_1,
  k_cycle_age_2,
  k_cycle_speed_1,
  k_cycle_speed_2,
  k_age_speed_1,
  k_age_speed_2,
  k_cycle_age_speed_1,
  k_cycle_age_speed_2,
  k_cycle_age_speed_3,
  k_cycle_ht_1,
  k_cycle_ht_2,
  k_ht,
  k_strlen,
  k_cycle_strlen_1,
  k_cycle_strlen_2,
  # k_cycle_re,
  cycle_age
) {
  
  # funargs <- as.list(match.call())[-1]
  # if(any(unlist(funargs)<3) & unlist(funargs)>0) 
  #   return(do.call("replaceScore", lapply(funargs, function(x) pmax(3,x))))
  
  k_cycle <- roundBelow3(k_cycle)
  k_age <- roundBelow3(k_age)
  k_speed <- roundBelow3(k_speed)
  k_cycle_age_1 <- roundBelow3(k_cycle_age_1)
  k_cycle_age_2 <- roundBelow3(k_cycle_age_2)
  k_cycle_speed_1 <- roundBelow3(k_cycle_speed_1)
  k_cycle_speed_2 <- roundBelow3(k_cycle_speed_2)
  k_age_speed_1 <- roundBelow3(k_age_speed_1)
  k_age_speed_2 <- roundBelow3(k_age_speed_2)
  k_cycle_age_speed_1 <- roundBelow3(k_cycle_age_speed_1)
  k_cycle_age_speed_2 <- roundBelow3(k_cycle_age_speed_2)
  k_cycle_age_speed_3 <- roundBelow3(k_cycle_age_speed_3)
  k_cycle_ht_1 <- roundBelow3(k_cycle_ht_1)
  k_cycle_ht_2 <- roundBelow3(k_cycle_ht_2)
  k_ht <- roundBelow3(k_ht)
  k_strlen <- roundBelow3(k_strlen)
  k_cycle_strlen_1 <- roundBelow3(k_cycle_strlen_1)
  k_cycle_strlen_2 <- roundBelow3(k_cycle_strlen_2)
  # k_cycle_re <- roundBelow3(k_cycle_re)
  
  bs <-  "cr"
  
  form <-  paste0("val ~ ",
                  "ti (cycle, k = k_cycle, bs = bs) + ",
                  "ti (age, k = k_age, bs = bs) + ",
                  "ti (speed, k = k_speed, bs = bs) + ",
                  "ti(ht, k = k_ht, bs = bs) + ",
                  "ti(strlen, k = k_strlen, bs = bs) + ",
                  "sex ")
  
  if(all(c(k_cycle_age_1, 
           k_cycle_age_2)>0))
    form <- paste0(form, 
                   "+ ti (cycle, age, k = c(k_cycle_age_1, k_cycle_age_2), bs = bs)")
  if(all(c(k_cycle_speed_1, 
           k_cycle_speed_2)>0))
    form <- paste0(form, 
                   "+ ti (cycle, speed, k = c(k_cycle_speed_1, k_cycle_speed_2),  bs = bs)")
  if(all(c(k_age_speed_1, 
           k_age_speed_2)>0))
    form <- paste0(form, 
                   "+ ti (age, speed,  k = c(k_age_speed_1, k_age_speed_2),  bs = bs)")
  if(all(c(
    k_cycle_age_1, 
    k_cycle_age_2,
    k_cycle_speed_1, 
    k_cycle_speed_2,
    k_age_speed_1, 
    k_age_speed_2,
    k_cycle_age_speed_1, 
    k_cycle_age_speed_2,
    k_cycle_age_speed_3)>0))
    form <- paste0(form, 
                   "+ ti (cycle, speed, age,  k = c(k_cycle_age_speed_1, k_cycle_age_speed_2, k_cycle_age_speed_3), bs = bs)"
    )
  if(all(c(k_cycle_ht_1, 
           k_cycle_ht_2)>0))
    form <- paste0(form, 
                   "+ ti (cycle, ht, k = c(k_cycle_ht_1, k_cycle_ht_2), bs = bs)")
  if(all(c(k_cycle_strlen_1, 
           k_cycle_strlen_2)>0))
    form <- paste0(form, 
                   "+ ti (cycle, strlen, k = c(k_cycle_strlen_1, k_cycle_strlen_1), bs = bs)")
  # if(k_cycle_re>0)
  #   form <- paste0(form, 
  #                  "+ ti (cycle, k = k_cycle_re, by = study, bs = 're')")
  
  form <- as.formula(form)
  
  pr <- try({
    
    mod <- bam (form,
                data = train,
                discrete = TRUE,
                family = scat()
    )
    
    predict(mod, newdata = test)#, exclude = "s(subj)")
    
  })
  
  if(class(pr)=="try-error") score <- NA else{
    
    test$pr <- pr
    predMat <- test %>% dplyr::select(-val) %>% spread(cycle, pr) %>% dplyr::select(`1`:`101`) %>% as.matrix()
    score <- -mean(relRMSE(trueMat, predMat), na.rm=T)
    
    
  }
  
  return(list(Score = score))
}

replaceScore <- scoringFunction

bounds <- list( 
  k_cycle = c(5L,25L), 
  k_age = c(5L,20L),
  k_speed = c(5L,20L),
  k_cycle_age_1 = c(0L,25L),
  k_cycle_age_2 = c(0L,20L),
  k_cycle_speed_1 = c(0L,25L),
  k_cycle_speed_2 = c(0L,6L),
  k_age_speed_1 = c(0L,20L),
  k_age_speed_2 = c(0L,6L),
  k_cycle_age_speed_1 = c(0L,15L),
  k_cycle_age_speed_2 = c(0L,10L),
  k_cycle_age_speed_3 = c(0L,6L),
  k_cycle_ht_1 = c(0L,25L),
  k_cycle_ht_2 = c(0L,15L),
  k_cycle_strlen_1 = c(0L,15L),
  k_cycle_strlen_2 = c(0L,15L),
  k_ht = c(5L,15L),
  k_strlen = c(5L, 20L)#,
  #k_cycle_re = c(5L,25L)
)

# Start BO ------------------------------------------------------------------------

nrClusters <- 30
nrEpochs <- 10

library(doParallel)
cl <- makeCluster(nrClusters)
registerDoParallel(cl)
clusterExport(cl,c('train','test','trueMat','relRMSE', 'RMSE', 'integrate_fun', 'roundBelow3'))
clusterEvalQ(cl,expr= {
  library(mgcv)
  library(tidyr)
  library(dplyr)
})

set.seed(42)

tWithPar <- system.time(
  optObj <- bayesOpt(
    FUN = scoringFunction,
    bounds = bounds,
    initPoints = nrClusters,
    iters.n = nrClusters * nrEpochs,
    iters.k = nrClusters,
    parallel = TRUE,
    verbose = 2,
    errorHandling = "continue"
  )
)
stopCluster(cl)
registerDoSEQ()

```

## Tune distribution family

### Ankle

```{r}

fams <- c(
  "NO", "GU", "RG" ,"LO", "NET", "TF", "TF2", "PE","PE2", 
  "SN1", "SN2", "exGAUS", "SHASH", "SHASHo","SHASHo2", 
  "EGB2", "JSU", "JSUo", "SEP1", "SEP2", "SEP3", "SEP4", 
  "ST1", "ST2", "ST3", "ST4", "ST5", "SST", "GT"
)

# check suitable distributions

## ankle
data <- readRDS("output/ankle_splitted.RDS")
train <- do.call("rbind", data[c(1,3)])
test <- data[[2]]
test <- test %>% arrange(subj, cycle)
trueMat <- test %>% spread(cycle, val) %>% dplyr::select(`21`:`69`) %>% as.matrix()

bo_ankle <- readRDS("output/BO_ankle.RDS")
df_bo_ankle <- bo_ankle$scoreSummary %>% 
  # drop the ones that did not work
  filter(Score > -100) %>% 
  mutate(Score = -Score) %>% 
  filter(Score < 0.25)

best_setting <- df_bo_ankle %>% 
  arrange(Score) %>% 
  dplyr::select(k_cycle:Score) %>%  
  dplyr::select(k_cycle:k_strlen) %>% 
  head(1) %>% c()

form <- do.call(settings_to_formula, best_setting)

form <- as.formula(paste0("val ~ ba(", form, ")"))

form.sigma <- ~ ba( ~ ti(cycle, bs = "cr", k = 20))

res <- mclapply(fams, function(fam){
  
  mod <- gamlss(form, 
                sigma.formula = form.sigma,
                family = fam,
                discrete = TRUE,
                data = train,
                n.cyc = 200,
                trace = TRUE)
  
  pr <- predict(mod, newdata = test, what = "mu")
  test$pr <- pr
  predMat <- test %>% dplyr::select(-val) %>% spread(cycle, pr) %>% dplyr::select(`21`:`69`) %>% as.matrix()
  score <- mean(relRMSE(trueMat, predMat), na.rm=T)
  
  return(score)
  
}, mc.cores = length(fams))

saveRDS(res, "output/dist_comparison_ankle.RDS")

data.frame(family = fams, score = as.numeric(unlist(res))) %>% arrange(score)

```

### Knee

```{r}

fams <- c(
  "NO", "GU", "RG" ,"LO", "NET", "TF", "TF2", "PE","PE2", 
  "SN1", "SN2", "exGAUS", "SHASH", "SHASHo","SHASHo2", 
  "EGB2", "JSU", "JSUo", "SEP1", "SEP2", "SEP3", "SEP4", 
  "ST1", "ST2", "ST3", "ST4", "ST5", "SST", "GT"
)

# check suitable distributions

## knee
data <- readRDS("output/knee_splitted.RDS")
train <- do.call("rbind", data[c(1,3)])
test <- data[[2]]
test <- test %>% arrange(subj, cycle)
trueMat <- test %>% spread(cycle, val) %>% dplyr::select(`1`:`101`) %>% as.matrix()

bo_knee <- readRDS("output/BO_knee.RDS")
df_bo_knee <- bo_knee$scoreSummary %>% 
  # drop the ones that did not work
  filter(Score > -100) %>% 
  mutate(Score = -Score) %>% 
  filter(Score < 0.25)

best_setting <- df_bo_knee %>% 
  arrange(Score) %>% 
  dplyr::select(k_cycle:Score) %>%  
  dplyr::select(k_cycle:k_strlen) %>% 
  head(1) %>% c()

form <- do.call(settings_to_formula, best_setting)

form <- as.formula(paste0("val ~ ba(", form, ")"))

form.sigma <- ~ ba( ~ ti(cycle, bs = "cr", k = 20))

res <- mclapply(fams, function(fam){
  
  mod <- gamlss(form, 
                sigma.formula = form.sigma,
                family = fam,
                discrete = TRUE,
                data = train,
                n.cyc = 200,
                trace = TRUE)
  
  pr <- predict(mod, newdata = test, what = "mu")
  test$pr <- pr
  predMat <- test %>% dplyr::select(-val) %>% spread(cycle, pr) %>% dplyr::select(`1`:`101`) %>% as.matrix()
  score <- mean(relRMSE(trueMat, predMat), na.rm=T)
  
  return(score)
  
}, mc.cores = length(fams))

saveRDS(res, "output/dist_comparison_knee.RDS")

data.frame(family = fams, score = as.numeric(unlist(res))) %>% arrange(score)
```

### Hip

```{r}
fams <- c(
  "NO", "GU", "RG" ,"LO", "NET", "TF", "TF2", "PE","PE2", 
  "SN1", "SN2", "exGAUS", "SHASH", "SHASHo","SHASHo2", 
  "EGB2", "JSU", "JSUo", "SEP1", "SEP2", "SEP3", "SEP4", 
  "ST1", "ST2", "ST3", "ST4", "ST5", "SST", "GT"
)

# check suitable distributions

## hip
data <- readRDS("output/hip_splitted.RDS")
train <- do.call("rbind", data[c(1,3)])
test <- data[[2]]
test <- test %>% arrange(subj, cycle)
trueMat <- test %>% spread(cycle, val) %>% dplyr::select(`1`:`101`) %>% as.matrix()

bo_hip <- readRDS("output/BO_hip.RDS")
df_bo_hip <- bo_hip$scoreSummary %>% 
  # drop the ones that did not work
  filter(Score > -100) %>% 
  mutate(Score = -Score) %>% 
  filter(Score < 0.25)

best_setting <- df_bo_hip %>% 
  arrange(Score) %>% 
  dplyr::select(k_cycle:Score) %>%  
  dplyr::select(k_cycle:k_strlen) %>% 
  head(1) %>% c()

form <- do.call(settings_to_formula, best_setting)

form <- as.formula(paste0("val ~ ba(", form, ")"))

form.sigma <- ~ ba( ~ ti(cycle, bs = "cr", k = 20))

res <- mclapply(fams, function(fam){
  
  mod <- gamlss(form, 
                sigma.formula = form.sigma,
                family = fam,
                discrete = TRUE,
                data = train,
                n.cyc = 200,
                trace = TRUE)
  
  pr <- predict(mod, newdata = test, what = "mu")
  test$pr <- pr
  predMat <- test %>% dplyr::select(-val) %>% spread(cycle, pr) %>% dplyr::select(`1`:`101`) %>% as.matrix()
  score <- mean(relRMSE(trueMat, predMat), na.rm=T)
  
  return(score)
  
}, mc.cores = length(fams))

saveRDS(res, "output/dist_comparison_hip.RDS")

data.frame(family = fams, score = as.numeric(unlist(res))) %>% arrange(score)
```


# Build final model

```{r}
## get the final model on the hold-out data set
rm(list=ls())
gc()

# function to create final model on hold-out set
# per joint
create_final_model <- function(joint = "ankle" ,
                               use_best_family = FALSE,
                               defined_family = "NO",
                               data = NULL,
                               withRE = "studysubj")
{

  ############# read hold-out set ##############
  if(is.null(data)){
    data <- readRDS(paste0("output/", joint, "_splitted.RDS"))
    this_data <<- do.call("rbind", data) # set global because gamlss does not find it otherwise
  }else{
    this_data <<- data
  }
  ##############################################

  ############# get best mu form ###############
  bo <- readRDS(paste0("output/BO_",joint,".RDS"))
  df_bo <- bo$scoreSummary %>%
    # drop the ones that did not work
    filter(Score > -100) %>%
    mutate(Score = -Score)

  best_setting <- df_bo %>%
    arrange(Score) %>%
    dplyr::select(k_cycle:Score) %>%
    dplyr::select(k_cycle:k_strlen) %>%
    head(1) %>% c()
  form <- do.call(settings_to_formula, best_setting)
  if(withRE=="subj"){
    form <- paste0("val ~ ba(", form, " + s(subj, bs = 're'))")
  }else if(withRE=="study")
  {
    form <- paste0("val ~ ba(", form, " + s(study, bs = 're'))")
  }else if(withRE=="studysubj"){
    form <- paste0("val ~ ba(", form, " + s(study, bs = 're') + s(study, subj, bs = 're'))")
  }else{
    form <- paste0("val ~ ba(", form, ")")
  }
  ##############################################

  ############# get best family ################
  if(use_best_family)
  {

    fams <- c(
      "NO", "GU", "RG" ,"LO", "NET", "TF", "TF2", "PE","PE2",
      "SN1", "SN2", "exGAUS", "SHASH", "SHASHo","SHASHo2",
      "EGB2", "JSU", "JSUo", "SEP1", "SEP2", "SEP3", "SEP4",
      "ST1", "ST2", "ST3", "ST4", "ST5", "SST", "GT"
    )

    bestFam <- fams[which.min(unlist(readRDS(paste0("output/dist_comparison_",joint,".RDS"))))]

  }else{

    bestFam <- defined_family

  }
  ##############################################


  #### define sig form and fit model ###########
  sig_formula <- "~ ba (~ ti(cycle, bs = 'cr', k = 20))"

  mod <- gamlss(formula = as.formula(form),
                family = bestFam,
                sigma.fo = as.formula(sig_formula),
                discrete = TRUE,
                data = this_data,
                n.cyc = 200,
                trace = TRUE)
  ##############################################

  return(list(mod,form))

}

# load original data
dat <- readRDS("output/df_clean_self.RDS") %>%
  filter (study != "lencioni") %>%
  group_by(subj, speed, age, sex, ht, wt, study)%>%
  ungroup () %>%
  mutate(sex = factor(sex),
         subj = factor(subj),
         study = factor(study)) %>%
  as.data.frame() %>%
  arrange (study, subj, joint, cond, speed, cycle)

# ankle
mod_ankle <- create_final_model(joint = "ankle", data = dat %>% filter(joint=="ankle") %>%
  filter(cycle < 70 & cycle > 20))
pdf("output/plots_ankle.pdf")
# old.par <- par()
# par(old.par)
term.plot(mod_ankle[[1]], what = "mu", ask = FALSE)
term.plot(mod_ankle[[1]], what = "sigma")
try(plot(mod_ankle[[1]]))
dev.off()

# hip
mod_hip <- create_final_model(joint = "hip", data = dat %>% filter(joint=="hip"))
pdf("output/plots_hip.pdf")
# old.par <- par()
# par(old.par)
term.plot(mod_hip[[1]], what = "mu", ask = FALSE)
term.plot(mod_hip[[1]], what = "sigma")
plot(mod_hip[[1]])
dev.off()

# knee
mod_knee <- create_final_model(joint = "knee", data = dat %>% filter(joint=="knee"))
pdf("output/plots_knee.pdf")
# old.par <- par()
# par(old.par)
term.plot(mod_knee[[1]], what = "mu", ask = FALSE)
term.plot(mod_knee[[1]], what = "sigma")
plot(mod_knee[[1]])
dev.off()


save (mod_ankle,
      mod_knee,
      mod_hip,
      file = "output/final_model.RData")

```




