---
title: "4_model_explore"
output:
  pdf_document: default
  html_notebook: default
editor_options:
  chunk_output_type: console
---

```{r, echo=FALSE}
knitr::opts_chunk$set(comment=NA, message=FALSE, echo=FALSE, fig.height=4, fig.width=4)
```

  
# Import library
  
```{r}

rm (list = ls())

# Helper
library (tidyverse)

# Import
library (rio)

# Exploration 
library (DataExplorer)
library (janitor)
library (arsenal)
library (ggforce)
library (moments)

# modelling
library (gamlss)
library (gamlss.add)
library (bamlss)

# parallel
library(doParallel)
library(foreach)
library (furrr)

# Plotting
library (distreg.vis)



```

# Import data

```{r, eval = FALSE}

output_dir <- "../output"
joint <- "ankle"
model <- "_gamlss_"
model_num <- "m7"

m7 <- readRDS (file.path(output_dir, paste0 (joint, model, model_num, ".RDS")))

distreg.vis::vis()

newdata <- expand.grid (age = seq(5, 85, 5),
                       speed = 0.6,
                       sex = factor ("m", levels = c("m", "f")),
                       cycle = c(1:101))

newdata$p <- predict (m7, 
              what = "mu",
              newdata = newdata,
              type = "response",
              data = df_ankle_downsamp)

f <- predict (m7,
              what = "mu",
              type = "terms",
              se.fit = TRUE)

```

# Analyse best models

## Ankle

```{r}
output_dir <- "../output"
joint <- "ankle"
model_name <- "best_model_"

df <- readRDS (file.path(output_dir, paste0("df_", joint,".RDS")))
model <- readRDS (file.path(output_dir, paste0 (model_name, joint, ".RDS")))

summary(model)

# plot(model)
# # because the plot takes very long
# Sys.sleep(10)

assign(paste0("df_",joint), df)

par(mfrow=c(2,2))
term.plot(model, pages = 2)

rm(model)

gc()
```

## Hip

```{r}
output_dir <- "../output"
joint <- "hip"
model_name <- "best_model_"

df <- readRDS (file.path(output_dir, paste0("df_", joint,".RDS")))
model <- readRDS (file.path(output_dir, paste0 (model_name, joint, ".RDS")))

summary(model)

# plot(model)
# # because the plot takes very long
# Sys.sleep(10)

assign(paste0("df_",joint), df)

par(mfrow=c(2,2))
term.plot(model, pages = 2)

rm(model)
rm(df)
gc()
```

## Knee

```{r}
output_dir <- "../output"
joint <- "knee"
model_name <- "best_model_"

df <- readRDS (file.path(output_dir, paste0("df_", joint,".RDS")))
model <- readRDS (file.path(output_dir, paste0 (model_name, joint, ".RDS")))

summary(model)

# plot(model)
# # because the plot takes very long
# Sys.sleep(10)

assign(paste0("df_",joint), df)

par(mfrow=c(2,2))
term.plot(model, pages = 2)

rm(model)
rm(df)
gc()
```
