---
title: "6_prediction"
output: html_notebook
editor_options: 
  chunk_output_type: console
---
  
# Import library
  
```{r}

rm (list = ls())

# Helper
library (tidyverse)
library (qwraps2)

# modelling
library (gamlss)
library (gamlss.add)
library(gamlss.dist)

# plot
library (itsadug)
library(mgcViz)

# Plotting
library (cowplot)
library (ggforce)
library (rainbow)

source ("code/measures_johnson.R")
```

# Import data

```{r}
# Models
load ("output/final_model.RData")

# Original data
dat <- readRDS("output/df_clean_self.RDS") %>%
  filter (study != "lencioni") %>%
  group_by(subj, speed, age, sex, ht, wt, study)%>%
  ungroup () %>%
  mutate(sex = factor(sex),
         subj = factor(subj),
         study = factor(study)) %>%
  as.data.frame() %>%
  arrange (study, subj, joint, cond, speed, cycle) 

```

# Descriptive statistics

```{r}

subj_per_jt <- dat %>%
  group_by(joint, study) %>%
  distinct (subj) %>%
  tally() %T>%
  print ()

dat_sub <- dat %>%
  filter (cycle == 1) %>%
  dplyr::select (-cond) %>%
  group_by(subj, study, age, sex, ht, wt) %>%   
  summarise_if(is.numeric, mean)


our_summary1 <-
  list("Age (years)" =
       list("mean (sd)" = ~ qwraps2::mean_sd(age, denote_sd = "paren")),
       "Height (m)" =
       list("mean (sd)" = ~ qwraps2::mean_sd(ht, denote_sd = "paren")),
        "Mass (kg)" =
       list("mean (sd)" = ~ qwraps2::mean_sd(wt, denote_sd = "paren")),
       "Sex" =
       list("Female" = ~ qwraps2::n_perc0(sex == "f"),
            "Male"  = ~ qwraps2::n_perc0(sex == "m")),
       "Speed (m/s)" = 
       list("mean (sd)" = ~ qwraps2::mean_sd(speed, denote_sd = "paren")),
       "Stride length (m)" = 
       list("mean (sd)" = ~ qwraps2::mean_sd(strlen, denote_sd = "paren")))

by_cyl <- summary_table(group_by(dat_sub, study), our_summary1) %>%
  as.data.frame() 

by_cyl$Variables <-  c("Age (years)",
                     "Height (m)",
                      "Mass (kg)",
                      "Sex-F",
                      "Sex-M",
                      "Speed (m/s)",
                      "Stride length (m)")

by_cyl <- dplyr::select (by_cyl, Variables, everything ())

my_path <- paste0("manuscript/table_", 
                  "summary",
                  ".docx")

ft <- flextable(by_cyl ) %>%
  autofit()

my_doc <- read_docx()  %>% 
  body_add_flextable(ft) %>%
  body_end_section_landscape()

print (my_doc, target = my_path)


```


# Set colour schems

```{r}
cbp2 <- c("#000000", "#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

# Plot original average data

```{r}
age_cut <- seq (10, 90, 10)
age_labels <- paste0 (paste (age_cut, "-", age_cut[-1])[-length (age_cut)], " (yo)")

speed_cut <- c(0.7, 1.0, 1.5, 1.9)
speed_labels <- paste (speed_cut, "-", speed_cut[-1])[-length (speed_cut)]

df_plot <- dat %>%
  filter(study != "lencioni") %>% # data reported dissimilar to others
  mutate (age_cat  = cut (age, age_cut, labels = age_labels, levels = age_labels),
          speed_cat  = cut (speed, speed_cut, labels = speed_labels, levels = speed_labels),
          joint = factor (joint, levels = c("ankle", "knee", "hip"))) %>%
  group_by(speed_cat, age_cat, joint, cycle) %>%
  summarize (val.mean = mean(val, na.rm = TRUE)) 

f <- ggplot (data = df_plot) +
  geom_line (aes (x = cycle, y = val.mean, colour = age_cat)) +
  labs (x = "% Stride",
        y = "Power (W/kg)") + 
  guides(colour = guide_legend(title="Age (yrs)")) +
  scale_color_manual(values = cbp2) + 
  facet_wrap_paginate(speed_cat~joint, ncol = 3, nrow = 3, scales = "free") +
  theme_cowplot()

n <- n_pages(f)

pdf (width = 10, height = 8, file = "manuscript/smfig_summary.pdf")

for (i in 1:n) {
  
  print (f + facet_wrap_paginate(speed_cat~joint, ncol = 3, nrow = 3,  page = i, scales = "free"))
  
}

dev.off()
```

```{r}

ggplot (dat) + 
  geom_line (aes (x = cycle, y = val, colour = subj)) + 
  facet_wrap(~ joint, ncol = 3) +
  guides (colour = FALSE)

dat_wide <- dat %>%
  pivot_wider(names_from = "cycle", values_from = "val")

by_group <- dat_wide %>%
  group_by(joint)

by_key <- by_group  %>%
  group_keys() 

df_plot <- by_group %>%
  group_split() %>%
  map (.%>% dplyr::select (-(subj:study)) %>% as.matrix)
  
names(df_plot) <- by_key$joint

df_plot <- list("Ankle" = df_plot[["ankle"]], 
                "Knee" = df_plot[["knee"]], 
                "Hip" = df_plot[["hip"]])

pdf (width = 20, height = 15, file = "manuscript/smfig_individual.pdf")

par(mfrow=c(2, 2))
par (mar = c(5, 7, 1, 1))

for(i in which(sapply(df_plot, is.matrix))){
  samp_dat <- df_plot[[i]] %>% t()
  samp_fds <- fds (x = c(1:101), 
                   y = samp_dat, 
                   xname = "% Stride", 
                   yname = paste0 (names (df_plot)[i], " power (W/kg)"))
  plot.fds(samp_fds, cex.axis = 1.5, cex.lab = 2)
  
}
dev.off()

```

# Get predictive error

```{r}

# Ankle

dat_a <- dat %>%
  filter (joint == "ankle") %>%
  filter (cycle > 20 & cycle < 70) %>%
  mutate (fit = predict (mod_ankle[[1]]))

obs <- dat_a %>%
  dplyr::select (subj, cycle, speed, val) %>%
  pivot_wider(names_from = "cycle",
              values_from = "val") %>%
  dplyr::select (-c(subj, speed)) %>%
  as.matrix()

pred <- dat_a %>%
  dplyr::select (subj, cycle, speed, fit) %>%
  pivot_wider(names_from = "cycle",
              values_from = "fit") %>%
  dplyr::select (-c(subj, speed)) %>%
  as.matrix()

error_a <- apply (all_measures(obs, pred), 2, mean)

# Knee

dat_a <- dat %>%
  filter (joint == "knee") %>%
  mutate (fit = predict (mod_knee[[1]]))

obs <- dat_a %>%
  dplyr::select (subj, cycle, speed, val) %>%
  pivot_wider(names_from = "cycle",
              values_from = "val") %>%
  dplyr::select (-c(subj, speed)) %>%
  as.matrix()

pred <- dat_a %>%
  dplyr::select (subj, cycle, speed, fit) %>%
  pivot_wider(names_from = "cycle",
              values_from = "fit") %>%
  dplyr::select (-c(subj, speed)) %>%
  as.matrix()

error_k <- apply (all_measures(obs, pred), 2, mean)

# Hip

dat_a <- dat %>%
  filter (joint == "hip") %>%
  mutate (fit = predict (mod_hip[[1]]))

obs <- dat_a %>%
  dplyr::select (subj, cycle, speed, val) %>%
  pivot_wider(names_from = "cycle",
              values_from = "val") %>%
  dplyr::select (-c(subj, speed)) %>%
  as.matrix()

pred <- dat_a %>%
  dplyr::select (subj, cycle, speed, fit) %>%
  pivot_wider(names_from = "cycle",
              values_from = "fit") %>%
  dplyr::select (-c(subj, speed)) %>%
  as.matrix()

error_h <- apply (all_measures(obs, pred), 2, mean)

bind(error_a, error_k, error_h)
```


# Smooth plots

## Smooth effect of age

```{r}

# Get smoother into a table

asmo <- get_modelterm (getSmo(mod_ankle[[1]]), 
                      select = 2, 
                      n.grid = 100,
                      se = TRUE,
                      as.data.frame = TRUE)

ksmo <- get_modelterm (getSmo(mod_knee[[1]]), 
                      select = 2, 
                      n.grid = 100,
                      se = TRUE,
                      as.data.frame = TRUE)

hsmo <- get_modelterm (getSmo(mod_hip[[1]]), 
                      select = 2, 
                      n.grid = 100,
                      se = TRUE,
                      as.data.frame = TRUE)

agesmo <- bind_rows (asmo, ksmo, hsmo) %>%
  mutate (joint = rep (c("ankle", "knee", "hip"), each = 100))

# Plot

pdf (width = 8, height = 5, file = "manuscript/fig1.pdf")

  ggplot (agesmo) +
    geom_line (aes (x = age, y = fit), size = 1) +
    geom_ribbon(aes (x = age, 
                     ymin = fit - 1.96 * se.fit, 
                     ymax = fit + 1.96 * se.fit), 
                fill = "lightblue", 
                alpha = 0.5) + 
    facet_wrap (~ joint, ncol = 2, scales = "fixed") + 
    labs (x = "Age (yo)",
          y = "Power (W/kg)") +
    theme_cowplot()

dev.off()
```

## Get peak values of smooth

```{r}
# Ankle maximum

peaks <- asmo[asmo$fit == max (asmo$fit),]
f <- peaks[,2]
lcl <- f - 1.96 * peaks[,3]
ucl <- f + 1.96 * peaks[,3]
age <- peaks[,1]
cat ("The max value of ankle is ", round (f, 2), "(95%CI", round (lcl, 2), "to", round (ucl, 2), ")", "which occurs at", round (age, 0), "(years)")

# Knee minimum

peaks <- ksmo[ksmo$fit == min (ksmo$fit),]
f <- peaks[,2]
lcl <- f - 1.96 * peaks[,3]
ucl <- f + 1.96 * peaks[,3]
age <- peaks[,1]
cat ("The max value of knee is ", round (f, 2), "(95%CI", round (lcl, 2), "to", round (ucl, 2), ")", "which occurs at", round (age, 0), "(years)")

# Hip minimum

peaks <- hsmo[hsmo$fit == min (hsmo$fit),]
f <- peaks[,2]
lcl <- f - 1.96 * peaks[,3]
ucl <- f + 1.96 * peaks[,3]
age <- peaks[,1]
cat ("The max value of hip is ", round (f, 2), "(95%CI", round (lcl, 2), "to", round (ucl, 2), ")", "which occurs at", round (age, 0), "(years)")

```


# Prediction inference

Set predictor values

```{r}

speed <- c(1, 1.5)
age <- seq (20, 80, 10)
strlen <- c(1.5)

```


## Waveform predictions

### Ankle

```{r}
smo <- getSmo(mod_ankle[[1]])

cycle <- 20:70

pp_ank <- get_predictions(smo, 
                      cond = list(age = age, speed = speed, cycle = cycle, strlen = strlen),
                      rm.ranef = TRUE,
                      se = TRUE) %>%
  mutate (age = factor (age),
          speed = factor (speed))

ank_plot <- ggplot (pp_ank) +
  geom_line (aes (x = cycle, y = fit, colour = age)) +
  scale_colour_manual(values = cbp2) +
  facet_wrap (~ speed, ncol = 2, scales = "fixed") + 
  xlim (1, 101) + 
  labs (x = "% Stride",
        y = "Power (W/kg)",
        colour = "Age (yo)") +
  guides (fill = FALSE) +
  theme_cowplot()


```

### Knee

```{r}

smo <- getSmo(mod_knee[[1]])

cycle <- 1:101

pp_kne <- get_predictions(smo, 
                      cond = list(age = age, speed = speed, cycle = cycle, strlen = strlen),
                      rm.ranef = TRUE,
                      se = TRUE) %>%
  mutate (age = factor (age),
          speed = factor (speed))

kne_plot <- ggplot (pp_kne) +
  geom_line (aes (x = cycle, y = fit, colour = age)) +
  scale_colour_manual(values = cbp2) +
  facet_wrap (~ speed, ncol = 2, scales = "fixed") + 
  labs (x = "% Stride",
        y = "Power (W/kg)",
        colour = "Age (yo)") +
  guides (fill = FALSE) +
  theme_cowplot()


```

### Hip

```{r}
smo <- getSmo(mod_hip[[1]])

cycle <- 1:101

pp_hip <- get_predictions(smo, 
                      cond = list(age = age, speed = speed, cycle = cycle, strlen = strlen),
                      rm.ranef = TRUE,
                      se = TRUE) %>%
  mutate (age = factor (age),
          speed = factor (speed))

hip_plot <- ggplot (pp_hip) +
  geom_line (aes (x = cycle, y = fit, colour = age)) +
  scale_colour_manual(values = cbp2) +
  facet_wrap ( ~ speed, ncol = 2, scales = "fixed") + 
  labs (x = "% Stride",
        y = "Power (W/kg)",
        colour = "Age (yo)") +
  guides (fill = FALSE) +
  theme_cowplot()

```

### Plot all joints waveform

```{r}
 pcol <- plot_grid (ank_plot + 
              theme(
                axis.text.x = element_blank(),
                axis.title.x = element_blank()) + 
                  theme(legend.position="none"),
            kne_plot +
              theme(
                axis.text.x = element_blank(),
                axis.title.x = element_blank()) + 
                  theme(legend.position="none"),
            hip_plot + 
                  theme(legend.position="none"),
            nrow = 3,
            ncol = 1,
            vjust = 1.5,
            hjust = 0,
            labels = "auto")

# extract the legend from one of the plots
legend <- get_legend(
  # create some space to the left of the legend
  ank_plot + theme(legend.box.margin = margin(0, 0, 0, 12))
)


pdf (width = 8, height = 8, file = "manuscript/fig2.pdf")

# add the legend to the row we made earlier. Give it one-third of 
# the width of one plot (via rel_widths).
plot_grid(pcol, legend, rel_widths = c(3, .4))

dev.off()
```


## Peaks inference

## Ankle

```{r}

a2 <-pp_ank %>%
  group_by(age, speed, strlen) %>%
  filter (fit == max (fit))

a2_plot <- ggplot (a2) +
  geom_point(aes (x = age, y = fit, group = 1)) +
  geom_line (aes (x = age, y = fit, group = 1)) + 
  geom_errorbar(aes (x = age, ymin = fit - CI, ymax = fit + CI)) + 
  facet_wrap ( ~ speed, ncol = 2, scales = "fixed") + 
  labs (x = "Age (yo)",
        y = "A2 (W/kg)") +
  theme_cowplot()

```

## Knee

```{r}

k2 <-pp_kne %>%
  filter (cycle > 10 & cycle < 40) %>%
  group_by(age, speed, strlen) %>%
  filter (fit == max (fit))

k2_plot <- ggplot (k2) +
  geom_point(aes (x = age, y = fit, group = 1)) +
  geom_line (aes (x = age, y = fit, group = 1)) + 
  geom_errorbar(aes (x = age, ymin = fit - CI, ymax = fit + CI)) + 
  facet_wrap ( ~ speed, ncol = 2, scales = "fixed") + 
  labs (x = "Age (yo)",
        y = "K2 (W/kg)") +
  theme_cowplot()

```

## hip

```{r}
# H1
h1 <-pp_hip %>%
  filter (cycle > 5 & cycle < 40) %>%
  group_by(age, speed, strlen) %>%
  filter (fit == max (fit))

h1_plot <- ggplot (h1) +
  geom_point(aes (x = age, y = fit, group = 1)) +
  geom_line (aes (x = age, y = fit, group = 1)) + 
  geom_errorbar(aes (x = age, ymin = fit - CI, ymax = fit + CI)) + 
  facet_wrap ( ~ speed, ncol = 2, scales = "fixed") + 
  labs (x = "Age (yo)",
        y = "H1 (W/kg)") +
  theme_cowplot()

# H3
h3 <-pp_hip %>%
  filter (cycle > 55 & cycle < 80) %>%
  group_by(age, speed, strlen) %>%
  filter (fit == max (fit))

h3_plot <- ggplot (h3) +
  geom_point(aes (x = age, y = fit, group = 1)) +
  geom_line (aes (x = age, y = fit, group = 1)) + 
  geom_errorbar(aes (x = age, ymin = fit - CI, ymax = fit + CI)) + 
  facet_wrap ( ~ speed, ncol = 2, scales = "fixed") + 
  labs (x = "Age (yo)",
        y = "H3 (W/kg)") +
  theme_cowplot()

```

## Plot discrete powers

```{r}

pdf (width = 8, height = 5, file = "manuscript/fig3.pdf")

 plot_grid (a2_plot + 
              theme(
                axis.text.x = element_blank(),
                axis.title.x = element_blank()),
            k2_plot +
              theme(
                axis.text.x = element_blank(),
                axis.title.x = element_blank()),
            h1_plot,
            h3_plot ,
            nrow = 2,
            ncol = 2,
            vjust = 1.5,
            hjust = 0,
            align = "v",
            labels = "auto")

dev.off()
```

## Report peaks

```{r}
# Ankle
## 1m/s

row_of_peak <- a2 %>% 
  ungroup () %>% 
  filter (speed == 1) %>% 
  slice_max(fit) 

age_at_peak <- row_of_peak %>% 
  pluck ("age") %>%
  as.character() %>%
  as.numeric()

fit <- row_of_peak %>%
  pluck ("fit")%>%
  round (2)

ci <- row_of_peak %>%
  pluck ("CI") %>%
  round (2)

cat ("Power peaked at the age of", age_at_peak, "with a value of ", fit, "(95%CI", fit - ci, "to", fit + ci, ")")

## 1.5m/s

row_of_peak <- a2 %>% 
  ungroup () %>% 
  filter (speed == 1.5) %>% 
  slice_max(fit) 

age_at_peak <- row_of_peak %>% 
  pluck ("age") %>%
  as.character() %>%
  as.numeric()

fit <- row_of_peak %>%
  pluck ("fit")%>%
  round (2)

ci <- row_of_peak %>%
  pluck ("CI") %>%
  round (2)

cat ("Power peaked at the age of", age_at_peak, "with a value of ", fit, "(95%CI", fit - ci, "to", fit + ci, ")")

# Knee
## 1m/s

row_of_peak <- k2 %>% 
  ungroup () %>% 
  filter (speed == 1) %>% 
  slice_max(fit) 

age_at_peak <- row_of_peak %>% 
  pluck ("age") %>%
  as.character() %>%
  as.numeric()

fit <- row_of_peak %>%
  pluck ("fit")%>%
  round (2)

ci <- row_of_peak %>%
  pluck ("CI") %>%
  round (2)

cat ("Power peaked at the age of", age_at_peak, "with a value of ", fit, "(95%CI", fit - ci, "to", fit + ci, ")")

## 1.5m/s

row_of_peak <- k2 %>% 
  ungroup () %>% 
  filter (speed == 1.5) %>% 
  slice_max(fit) 

age_at_peak <- row_of_peak %>% 
  pluck ("age") %>%
  as.character() %>%
  as.numeric()

fit <- row_of_peak %>%
  pluck ("fit")%>%
  round (2)

ci <- row_of_peak %>%
  pluck ("CI") %>%
  round (2)

cat ("Power peaked at the age of", age_at_peak, "with a value of ", fit, "(95%CI", fit - ci, "to", fit + ci, ")")

# Hip H1
## 1m/s

row_of_peak <- h1 %>% 
  ungroup () %>% 
  filter (speed == 1) %>% 
  slice_max(fit) 

age_at_peak <- row_of_peak %>% 
  pluck ("age") %>%
  as.character() %>%
  as.numeric()

fit <- row_of_peak %>%
  pluck ("fit")%>%
  round (2)

ci <- row_of_peak %>%
  pluck ("CI") %>%
  round (2)

cat ("Power peaked at the age of", age_at_peak, "with a value of ", fit, "(95%CI", fit - ci, "to", fit + ci, ")")

## 1.5m/s

row_of_peak <- h1 %>% 
  ungroup () %>% 
  filter (speed == 1.5) %>% 
  slice_max(fit) 

age_at_peak <- row_of_peak %>% 
  pluck ("age") %>%
  as.character() %>%
  as.numeric()

fit <- row_of_peak %>%
  pluck ("fit")%>%
  round (2)

ci <- row_of_peak %>%
  pluck ("CI") %>%
  round (2)

cat ("Power peaked at the age of", age_at_peak, "with a value of ", fit, "(95%CI", fit - ci, "to", fit + ci, ")")

# Hip H3
## 1m/s

row_of_peak <- h3 %>% 
  ungroup () %>% 
  filter (speed == 1) %>% 
  slice_max(fit) 

age_at_peak <- row_of_peak %>% 
  pluck ("age") %>%
  as.character() %>%
  as.numeric()

fit <- row_of_peak %>%
  pluck ("fit")%>%
  round (2)

ci <- row_of_peak %>%
  pluck ("CI") %>%
  round (2)

cat ("Power peaked at the age of", age_at_peak, "with a value of ", fit, "(95%CI", fit - ci, "to", fit + ci, ")")

## 1.5m/s

row_of_peak <- h3 %>% 
  ungroup () %>% 
  filter (speed == 1.5) %>% 
  slice_max(fit) 

age_at_peak <- row_of_peak %>% 
  pluck ("age") %>%
  as.character() %>%
  as.numeric()

fit <- row_of_peak %>%
  pluck ("fit")%>%
  round (2)

ci <- row_of_peak %>%
  pluck ("CI") %>%
  round (2)

cat ("Power peaked at the age of", age_at_peak, "with a value of ", fit, "(95%CI", fit - ci, "to", fit + ci, ")")
```

